default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 20010809

development:
  <<: *default
  database: sports_management_development

test:
  <<: *default
  database: sports_management_development_test

production:
  primary: &primary_config
    <<: *default
    url: <%= ENV['DATABASE_URL'] %>
    username: postgres
    password: 20010809

  cable:
    <<: *primary_config

  queue:
    <<: *primary_config

  cache:
    <<: *primary_config